# Generated by Django 3.2 on 2021-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Stock Price'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Stock Price'),
        ),
    ]
