# Generated by Django 3.2 on 2021-09-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Stock Name'),
        ),
    ]
